In [7]:
import requests
from bs4 import BeautifulSoup
website="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
result=requests.get(website) #requests send karie che,data leva mate (object formate ma data aavshe)
content=result.text #object to text
# content # output string ma aavshe
soup=BeautifulSoup(content,"html.parser") #string to html 
# soup
# print(soup.prettify)

In [23]:
name=[]
price=[]
detail=soup.find_all('div',class_='card thumbnail')
for i in detail:
    name.append(i.find('a').text.strip())
    price.append(i.find('span').text.strip())
data={"leptop_name : ":name,"Leptop_price : ":price}
import pandas as pd
df=pd.DataFrame(data)
df.to_csv('Leptop.csv')

# 30 most popular movie

In [41]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
with open("30 Most Popular Movies.html","r",encoding="utf-8") as file:
    content=file.read()
 
soup=BeautifulSoup(content,'html.parser')
box=soup.find_all('div',class_='article_movie_title')
Film_name=[]
rating=[]
for i1 in box:
    Film_name.append(i1.find('a').text.strip())
    rating.append(i1.find('span',class_='tMeterScore').text.strip())

data={"Film_Name : ":Film_name,"Film_Rating : ":rating}
df=pd.DataFrame(data)
df.to_csv('A30_movie.csv',index=False)
df

                               Film_Name :  Film_Rating :
0          Transformers: Rise of the Beasts            53%
1       Spider-Man: Across the Spider-Verse            96%
2                        The Little Mermaid            67%
3                             The Boogeyman            63%
4     Are You There God? It's Me, Margaret.            99%
5                                    Fast X            56%
6                                BlackBerry            98%
7                               The Machine            27%
8                                   Reality            92%
9                               Flamin' Hot            68%
10           Guardians of the Galaxy Vol. 3            82%
11                                Blue Jean            94%
12                               Past Lives            97%
13              The Super Mario Bros. Movie            58%
14                 Avatar: The Way of Water            76%
15               Guy Ritchie's The Covenant            83%
16                                Bumblebee            91%
17                                Nefarious            33%
18                                     Sisu            93%
19                     You Hurt My Feelings            95%
20                     John Wick: Chapter 4            94%
21                           Leave No Trace            80%
22                          About My Father            36%
23  Dungeons & Dragons: Honor Among Thieves            90%
24                             Transformers            57%
25                                 My Fault
26                         A Beautiful Life            50%
27     The Angry Black Girl and Her Monster            88%
28                                  Missing            87%
29                                      Air            92%

In [37]:
df.isna().sum()

Film_Name :       0
Film_Rating :     0
dtype: int64

#  Certified used Mercedes-Benz for sale

1. name
2.milage
3.price
4.rating

In [61]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
with open('Certified used Mercedes-Benz for sale.html','r',encoding='utf-8')as file:
    content=file.read()

soup=BeautifulSoup(content,'html.parser')
box=soup.find_all('div',class_='vehicle-details')
name=[]
milage=[]
price=[]
rat=[]
for i in box:
    name.append(i.find('h2',class_='title').text.strip())
    milage.append(i.find('div',class_='mileage').text.strip())
    price.append(i.find('span',class_='primary-price').text.strip())
    # rat.append(i.find('span',class_='sds-rating__count').text.strip())
    r=i.find('span',class_='sds-rating__count')

    if r:
        rat.append(r.text.strip())

    else:
        rat.append("not available")


data={"Name : ":name,"Milage : ":milage,"Prie : ":price,"Rating : ":rat}  
df=pd.DataFrame(data)
df.to_csv('car.csv',index=False)

In [ ]:
# 1.name
# 2.rating
# 3.descount price
# 4.actual price

In [85]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
with open('flipkart.html','r',encoding='utf-8')as file:
    content=file.read()
name=[]
rating=[]
descount=[]
actual=[]
soup=BeautifulSoup(content,'html.parser')
box=soup.find_all('div',class_='col col-7-12')
for i in box:
    name.append(i.find('div',class_='_4rR01T').text.strip())
    rating.append(i.find('div',class_='_3LWZlK').text.strip())
    descount.append(i.find('div',class_='_30jeq3 _1_WHN1'))
    a=i.find('div',class_='_3I9_wc _27UcVY')
    if a:
        actual.append(a.text.strip())
    else:
         actual.append("not available")

        
        
data={"name ":name,"rating ":rating,"descount":descount,"actual ":actual}  
df=pd.DataFrame(data)
df.to_csv('flip.csv',index=False)
# name
# rating
# descount
# actual

In [84]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
with open("flipkart.html","r",encoding="utf-8") as file:
    content=file.read()
soup=BeautifulSoup(content,'html.parser')  
box=soup.find_all('div',class_="_3pLy-c row")
mobile_name=[]
rating=[]
discount_price=[]
actual_price=[]
for i in box:
    mobile_name.append(i.find('div',class_='_4rR01T').text.strip())
    rating.append(i.find('div',class_='_3LWZlK').text.strip())
    discount_price.append(i.find('div',class_='_30jeq3 _1_WHN1').text.strip())
    a=i.find('div',class_='_3I9_wc _27UcVY')
    if a:
        actual_price.append(a.text.strip())
    else:
         actual_price.append("Missing")
data={"mobile_name":mobile_name,"rating":rating,"discount_price":discount_price,"actual_price":actual_price}
import pandas as pd
df=pd.DataFrame(data)
df

,mobile_name,rating,discount_price,actual_price
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,"₹39,999","₹40,999"
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,"₹39,999","₹40,999"
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,"₹49,999","₹1,01,999"
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,"₹44,999","₹95,999"
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,"₹49,999","₹74,999"
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,"₹49,999","₹74,999"
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,"₹40,999","₹45,999"
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,"₹46,999","₹47,999"
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,"₹49,999","₹1,01,999"
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,"₹47,349","₹47,999"
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,"₹38,849","₹47,999"
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,"₹44,999","₹95,999"
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,"₹49,999","₹57,990"
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,"₹47,999","₹57,990"
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,"₹48,999",Missing
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,"₹46,999",Missing
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,"₹49,999",Missing
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,"₹46,999","₹48,900"
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,"₹49,999",Missing
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,"₹43,990","₹79,990"
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,"₹43,900","₹79,990"
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,"₹49,999","₹57,999"
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,"₹48,999","₹54,990"
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,"₹48,880","₹84,999"